// src/components/CanvasEffects/react/MatrixRain.tsx
import { useEffect, useRef, type CSSProperties } from 'react'
import { useCanvasEffect } from '@/hooks/use-canvas-effect'

export interface MatrixRainProps {
  /** Color of the bright head square */
  headColor?: string
  /** Base hue (0–360) for the falling trail (uses HSL) */
  trailHue?: number
  /** Column width in px */
  gap?: number
  /** Fall speed multiplier */
  speed?: number
  /** Number of squares in each column's tail */
  tailLength?: number
  className?: string
  style?: CSSProperties
}

/**
 * MatrixRain — Falling column simulation
 *
 * Each column has a bright head and a fading tail. Head color, trail
 * hue, column width, speed, and tail length are all configurable.
 *
 * @example
 * <MatrixRain headColor="#ffffff" trailHue={120} gap={16} speed={1} tailLength={10} />
 */
export function MatrixRain({
  headColor = '#ffffff',
  trailHue = 120,
  gap = 16,
  speed = 1,
  tailLength = 10,
  className,
  style,
}: MatrixRainProps) {
  const ref          = useRef<HTMLCanvasElement>(null)
  const headColorRef = useRef(headColor)
  const trailHueRef  = useRef(trailHue)
  const gapRef       = useRef(gap)
  const speedRef     = useRef(speed)
  const tailRef      = useRef(tailLength)

  useEffect(() => { headColorRef.current = headColor  }, [headColor])
  useEffect(() => { trailHueRef.current  = trailHue   }, [trailHue])
  useEffect(() => { gapRef.current       = gap        }, [gap])
  useEffect(() => { speedRef.current     = speed      }, [speed])
  useEffect(() => { tailRef.current      = tailLength }, [tailLength])

  useCanvasEffect(ref, (ctx, el) => {
    const cols: number[] = []

    return (_dt, frames) => {
      const GAP  = gapRef.current
      const TAIL = tailRef.current
      const W = el.width, H = el.height
      // Compounded over the frame delta so trail length is refresh-rate independent.
      ctx.fillStyle = `rgba(0,0,0,${1 - Math.pow(1 - 0.18, frames)})`
      ctx.fillRect(0, 0, W, H)
      const rows = Math.ceil(H / GAP), size = GAP - 3

      // Adjust column array width if needed
      const needed = Math.ceil(W / Math.max(1, GAP))
      while (cols.length < needed) cols.push(-Math.floor(Math.random() * 12))
      if (cols.length > needed) cols.length = needed

      cols.forEach((head, c) => {
        for (let i = 0; i < TAIL; i++) {
          const row = Math.floor(head) - i
          if (row < 0 || row > rows) continue
          const bright = 1 - i / TAIL
          ctx.globalAlpha = bright
          ctx.fillStyle = i === 0
            ? headColorRef.current
            : `hsl(${trailHueRef.current} 100% ${28 + bright * 28}%)`
          ctx.fillRect(c * GAP + 1, row * GAP + 1, size, size)
        }
        cols[c] = head >= rows + TAIL ? -Math.floor(Math.random() * 12) : head + 0.28 * speedRef.current * frames
      })

      ctx.globalAlpha = 1
    }
  })

  return (
    <canvas
      ref={ref}
      className={className}
      style={{ display: 'block', width: '100%', height: '100%', background: '#000', ...style }}
    />
  )
}

// src/components/CanvasEffects/vue/MatrixRain.vue
<script setup lang="ts">
/**
 * MatrixRain — Falling column simulation
 * Compatible with Vue 3 and Nuxt 3.
 *
 * @example
 * <MatrixRain head-color="#ffffff" :trail-hue="120" :gap="16" :speed="1" :tail-length="10" />
 */
import { ref } from 'vue'
import { useCanvasEffect } from '@/composables/useCanvasEffect'

const props = withDefaults(defineProps<{
  headColor?: string
  trailHue?: number
  gap?: number
  speed?: number
  tailLength?: number
}>(), { headColor: '#ffffff', trailHue: 120, gap: 16, speed: 1, tailLength: 10 })

const canvasRef = ref<HTMLCanvasElement | null>(null)

useCanvasEffect(canvasRef, (ctx, el) => {

  let cols: number[] = []

  return (_dt, frames) => {
    const GAP = props.gap, TAIL = props.tailLength, W = el.width, H = el.height
    // Compounded over the frame delta so trail length is refresh-rate independent.
    ctx.fillStyle = `rgba(0,0,0,${1 - Math.pow(1 - 0.18, frames)})`
    ctx.fillRect(0, 0, W, H)
    const rows = Math.ceil(H / GAP), size = GAP - 3
    const needed = Math.ceil(W / GAP)
    while (cols.length < needed) cols.push(-Math.floor(Math.random() * 12))
    if (cols.length > needed) cols.length = needed

    cols.forEach((head, c) => {
      for (let i = 0; i < TAIL; i++) {
        const row = Math.floor(head) - i
        if (row < 0 || row > rows) continue
        const bright = 1 - i / TAIL
        ctx.globalAlpha = bright
        ctx.fillStyle = i === 0
          ? props.headColor
          : `hsl(${props.trailHue} 100% ${28 + bright * 28}%)`
        ctx.fillRect(c * GAP + 1, row * GAP + 1, size, size)
      }
      cols[c] = head >= rows + TAIL ? -Math.floor(Math.random() * 12) : head + 0.28 * props.speed
    })
    ctx.globalAlpha = 1
  }
})
</script>

<template>
  <canvas ref="canvasRef" style="display:block;width:100%;height:100%;background:#000" />
</template>
