// src/components/CanvasEffects/react/MouseRipple.tsx
import { useEffect, useRef, type CSSProperties } from 'react'
import { useCanvasEffect } from '@/hooks/use-canvas-effect'

export interface MouseRippleProps {
  /** Dot fill color */
  color?: string
  /** Distance between dot centers in px */
  gap?: number
  /** Radius of the ripple influence zone in px */
  rippleRadius?: number
  /** Ripple wave speed multiplier */
  speed?: number
  className?: string
  style?: CSSProperties
}

/**
 * MouseRipple — Interactive dot-grid ripple
 *
 * Move the mouse over the canvas to send a sine ripple through
 * the dot grid. Dots outside the cursor zone stay at rest.
 *
 * @example
 * <MouseRipple color="#f59e0b" gap={24} rippleRadius={130} speed={1} />
 */
export function MouseRipple({
  color = '#f59e0b',
  gap = 24,
  rippleRadius = 130,
  speed = 1,
  className,
  style,
}: MouseRippleProps) {
  const ref           = useRef<HTMLCanvasElement>(null)
  const mouse         = useRef({ x: -999, y: -999 })
  const colorRef      = useRef(color)
  const gapRef        = useRef(gap)
  const radiusRef     = useRef(rippleRadius)
  const speedRef      = useRef(speed)

  useEffect(() => { colorRef.current  = color        }, [color])
  useEffect(() => { gapRef.current    = gap          }, [gap])
  useEffect(() => { radiusRef.current = rippleRadius }, [rippleRadius])
  useEffect(() => { speedRef.current  = speed        }, [speed])

  useCanvasEffect(ref, (ctx, el, signal) => {

    const onMove = (e: MouseEvent) => {
      const r = el.getBoundingClientRect()
      mouse.current = { x: e.clientX - r.left, y: e.clientY - r.top }
    }
    el.addEventListener('mousemove', onMove, { signal })

    let t = 0
    return (_dt, frames) => {
      const GAP = gapRef.current
      const W = el.offsetWidth, H = el.offsetHeight
      ctx.clearRect(0, 0, W, H)
      const cols = Math.ceil(W / GAP) + 1, rows = Math.ceil(H / GAP) + 1
      const { x: mx, y: my } = mouse.current
      const RAD = radiusRef.current

      for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) {
          const cx = c * GAP + GAP / 2, cy = r * GAP + GAP / 2
          const dx = cx - mx, dy = cy - my
          const dist = Math.sqrt(dx * dx + dy * dy)
          const ripple = Math.max(0, 1 - dist / RAD) * Math.sin(dist * 0.14 - t * 3.2)
          const size = Math.max(0, 3 + ripple * 9)
          ctx.globalAlpha = Math.max(0.1, Math.min(1, 0.25 + Math.abs(ripple) * 0.75))
          ctx.fillStyle = colorRef.current
          ctx.fillRect(cx - size / 2, cy - size / 2, size, size)
        }
      }

      ctx.globalAlpha = 1
      t += 0.06 * speedRef.current * frames
    }
    // Draws in CSS pixels; the scale transform is applied for us on resize.
  }, { coordinates: 'css' })

  return (
    <canvas
      ref={ref}
      className={className}
      style={{ display: 'block', width: '100%', height: '100%', cursor: 'crosshair', ...style }}
    />
  )
}

// src/components/CanvasEffects/vue/MouseRipple.vue
<script setup lang="ts">
/**
 * MouseRipple — Interactive dot-grid ripple
 * Compatible with Vue 3 and Nuxt 3.
 *
 * @example
 * <MouseRipple color="#f59e0b" :gap="24" :ripple-radius="130" :speed="1" />
 */
import { ref } from 'vue'
import { useCanvasEffect } from '@/composables/useCanvasEffect'

const props = withDefaults(defineProps<{
  color?: string
  gap?: number
  rippleRadius?: number
  speed?: number
}>(), { color: '#f59e0b', gap: 24, rippleRadius: 130, speed: 1 })

const canvasRef = ref<HTMLCanvasElement | null>(null)
useCanvasEffect(canvasRef, (ctx, el, signal) => {
  const mouse = { x: -999, y: -999 }


  const onMove = (e: MouseEvent) => {
    const r = el.getBoundingClientRect()
    mouse.x = e.clientX - r.left; mouse.y = e.clientY - r.top
  }
  el.addEventListener('mousemove', onMove, { signal })

  let t = 0
  return (_dt, frames) => {
    const GAP = props.gap, W = el.offsetWidth, H = el.offsetHeight, RAD = props.rippleRadius
    ctx.clearRect(0, 0, W, H)
    const cols = Math.ceil(W / GAP) + 1, rows = Math.ceil(H / GAP) + 1
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        const cx = c * GAP + GAP / 2, cy = r * GAP + GAP / 2
        const dx = cx - mouse.x, dy = cy - mouse.y
        const dist = Math.sqrt(dx * dx + dy * dy)
        const ripple = Math.max(0, 1 - dist / RAD) * Math.sin(dist * 0.14 - t * 3.2)
        const size = Math.max(0, 3 + ripple * 9)
        ctx.globalAlpha = Math.max(0.1, Math.min(1, 0.25 + Math.abs(ripple) * 0.75))
        ctx.fillStyle = props.color
        ctx.fillRect(cx - size / 2, cy - size / 2, size, size)
      }
    }
    ctx.globalAlpha = 1
    t += 0.06 * props.speed * frames
  }
  // Draws in CSS pixels; the scale transform is applied for us on resize.
}, { coordinates: 'css' })
</script>

<template>
  <canvas ref="canvasRef" style="display:block;width:100%;height:100%;cursor:crosshair" />
</template>
