// packages/vue/src/components/ui/Skeleton.vue
<script setup lang="ts">
import { computed } from 'vue'
import { cn } from '@/lib/utils'

type SkeletonVariant = 'pulse' | 'stamp' | 'blocks' | 'scan' | 'none'

const props = withDefaults(
  defineProps<{
    class?: string
    /**
     * pulse  — soft opacity breathe (the pre-v3.5 default)
     * stamp  — hard on/off, no interpolated fade
     * blocks — marching cells on a stepped loop
     * scan   — a hard bar sweeping across the block
     * none   — no motion at all
     */
    variant?: SkeletonVariant
  }>(),
  { variant: 'pulse' }
)

// Decorative placeholder — hidden from AT. Announce loading on the container
// instead (aria-busy / role="status"), not per-skeleton.
const variantClass = computed(
  () =>
    ({
      pulse: 'animate-pulse',
      stamp: 'bk-skeleton-stamp',
      blocks: 'bk-skeleton-blocks',
      scan: 'bk-skeleton-scan',
      none: '',
    })[props.variant]
)
</script>

<!--
  A comment here would make this a multi-root fragment and kill attribute
  fallthrough — keep the template to a single root element.
-->
<template>
  <div
    aria-hidden="true"
    :class="cn('bg-muted border-2 border-foreground/20', variantClass, props.class)"
  />
</template>

// src/components/ui/skeleton.tsx
/* eslint-disable react-refresh/only-export-components */
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const skeletonVariants = cva('bg-muted border-2 border-foreground/20', {
  variants: {
    variant: {
      /** Soft opacity breathe. The pre-v3.5 default. */
      pulse: 'animate-pulse',
      /** Hard on/off — no interpolated fade. */
      stamp: 'bk-skeleton-stamp',
      /** Marching cells on a stepped loop. */
      blocks: 'bk-skeleton-blocks',
      /** A hard bar sweeping across the block. */
      scan: 'bk-skeleton-scan',
      /** No motion at all. */
      none: '',
    },
  },
  defaultVariants: {
    variant: 'pulse',
  },
})

export interface SkeletonProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof skeletonVariants> {}

function Skeleton({ className, variant, ...props }: SkeletonProps) {
  return (
    <div
      // ponytail: decorative placeholder — hidden from AT. Announce loading on
      // the container instead (aria-busy / role="status"), not per-skeleton.
      aria-hidden="true"
      className={cn(skeletonVariants({ variant }), className)}
      {...props}
    />
  )
}

export { Skeleton, skeletonVariants }
